export const CIB_SYLLABUS = [
  { class_number: "Orientation", topic: "Basic knowledge Sharing", content_details: ["Basic knowledge Sharing about Culinary Industry & Professional Chef Course (F&B)"] },
  { class_number: "Class-01", topic: "Hygiene & Knife Skills", content_details: ["Theory: Hygiene, HACCP, Kitchen, Storage, Chef Knife", "Practical: Vegetable Cutting-Demonstration"] },
  { class_number: "Class-02", topic: "Equipment & Spices", content_details: ["Theory: Kitchen Equipment, Herbs, Utensils, Spices", "Practical: Vegetable Cutting & Knife Handling"] },
  { class_number: "Class-03", topic: "Vegetable Cutting", content_details: ["Student Practice Session"] },
  { class_number: "Class-04", topic: "Stocks & Soups", content_details: ["Stocks Making", "Vegetable Soup", "Sweet Corn Chicken Soup"] },
  { class_number: "Class-05", topic: "5 Mother Sauces", content_details: ["Marinara", "Espagnole", "Béchamel", "Velouté", "Hollandaise"] },
  { class_number: "Class-06", topic: "Continental Cuisine-I", content_details: ["Whole Chicken Cutting", "Lyonnaise Potato", "Meat Box", "Cream of Chicken Soup"] },
  { class_number: "Class-07", topic: "Continental Cuisine-II", content_details: ["Beef Steak", "Saute Vegetable", "Caesar Salad", "Mashed Potato"] },
  { class_number: "Class-08", topic: "Italian Cuisine-I", content_details: ["Italian Oven Baked Pasta", "Cheese Ball", "Italian Pasta Salad"] },
  { class_number: "Class-09", topic: "Thai Cuisine", content_details: ["Whole Fish Cutting", "Bruschetta al Pomodoro", "Thai Pineapple Fried Rice", "Thai Thick Soup", "Sweet & Sour Fish"] },
  { class_number: "Class-10", topic: "Practice Examination", content_details: ["Practice Examination Session"] },
  { class_number: "Class-11", topic: "Mexican Cuisine", content_details: ["Mexican Salad with Lemon Dressing", "Mexican Quesadilla", "Mexican Nachos", "Mexican Fried Rice"] },
  { class_number: "Class-12", topic: "French Cuisine", content_details: ["Chicken Quiche Lorraine", "French Salad", "Chicken Francese", "Roasted Potatoes"] },
  { class_number: "Class-13", topic: "Indian Cuisine-I", content_details: ["Chicken Tikka Kebab", "Hyderabadi Chicken Biryani", "Chole", "Bhature"] },
  { class_number: "Class-14", topic: "Indian Cuisine-II", content_details: ["Red Curry Gravy", "Mutton Rogan Josh", "Tandoori Chicken", "Naan Bread"] },
  { class_number: "Class-15", topic: "Practice Examination", content_details: ["Practice Examination Session"] },
  { class_number: "Class-16", topic: "Chinese Cuisine", content_details: ["Chicken Fried Rice", "Mixed Vegetable Curry", "Chicken Chow-Mein", "Vegetable Spring Roll"] },
  { class_number: "Class-17", topic: "Arabian Cuisine", content_details: ["Lebanese Hummus", "Arabian Kabsa", "Pita Bread", "Arabian Shawarma"] },
  { class_number: "Class-18", topic: "Korean Cuisine", content_details: ["Korean Spicy Fried Rice", "Korean Spicy Fried Chicken", "Korean Spicy Ramen", "Korean Egg Tomato Soup"] },
  { class_number: "Class-19", topic: "Breakfast", content_details: ["Continental Breakfast", "American Breakfast", "Arabian Breakfast", "Indian Breakfast"] },
  { class_number: "Class-20", topic: "Practice Examination", content_details: ["Practice Examination Session"] },
  { class_number: "Class-21", topic: "Sea Foods", content_details: ["Seafood Paella", "Calamari Fried Ring", "Spicy Chili Crab", "Sea Food Salad"] },
  { class_number: "Class-22", topic: "Japanese Cuisine", content_details: ["Japanese Sushi", "Egg Drop Soup", "Japanese Chicken Teriyaki", "Crispy Tempura Fried Prawn"] },
  { class_number: "Class-23", topic: "Burger Items & Sandwiches", content_details: ["Chicken Burger", "Beef Cheese Burger", "Club Sandwich", "Chicken & Vegetable Sandwich"] },
  { class_number: "Class-24", topic: "Turkish Cuisine", content_details: ["Turkish Bread", "Adana Kebab", "Lahm Bi Ajeen", "Turkish Whole Baked Fish"] },
  { class_number: "Class-25", topic: "Practice Examination", content_details: ["Practice Examination Session"] },
  { class_number: "Class-26", topic: "Italian Cuisine-II (Pizza)", content_details: ["Margherita Pizza", "Supreme Pizza", "Pizza-Italiano", "Italian Pepperoni Pizza"] },
  { class_number: "Class-27", topic: "Bengali Cuisine", content_details: ["Wedding Special Chicken Roast", "Plain Pulao", "Beef Rezala", "Bengali Salad + Borhani"] },
  { class_number: "Class-28", topic: "Bakery & Pastry-I", content_details: ["Sponge Cake with Decoration", "Pound Cake", "Sandwich Bread", "Swiss Roll"] },
  { class_number: "Class-29", topic: "Bakery & Pastry-II", content_details: ["Cake Frosting", "Cookies", "Dinner Roll", "Burger Bun, Chicken Bun"] },
  { class_number: "Class-30", topic: "Practice Examination", content_details: ["Practice Examination Session"] },
  { class_number: "Class-31", topic: "Beverage", content_details: ["10+ Beverage Items"] },
  { class_number: "Class-32", topic: "Carving Class", content_details: ["Special Carving Class on Vegetables & Fruits"] },
  { class_number: "Class-33", topic: "Dessert & Salad", content_details: ["Special Dessert & Salad Making for Exam Preparation"] },
  { class_number: "Class-34", topic: "Methods", content_details: ["International Cooking Methods Demonstration"] },
  { class_number: "Class-35", topic: "Practice", content_details: ["Methods Practice Session"] },
  { class_number: "Class-36", topic: "Practice", content_details: ["Methods Practice Session"] }
];